import { Game, Pick } from './types'

export const MOCK_GAMES: Game[] = [
  // NBA Playoffs
  {
    id: 'nba-1',
    sport: 'NBA',
    homeTeam: { name: 'Boston Celtics', abbreviation: 'BOS', record: '58-24' },
    awayTeam: { name: 'Miami Heat', abbreviation: 'MIA', record: '46-36' },
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    homeOdds: {
      moneyline: -165,
      spread: -4.5,
      spreadOdds: -110,
      total: 214.5,
      totalOddsOver: -110,
      totalOddsUnder: -110,
    },
    awayOdds: {
      moneyline: +140,
      spread: +4.5,
      spreadOdds: -110,
      total: 214.5,
      totalOddsOver: -110,
      totalOddsUnder: -110,
    },
    status: 'upcoming',
  },
  {
    id: 'nba-2',
    sport: 'NBA',
    homeTeam: { name: 'Denver Nuggets', abbreviation: 'DEN', record: '53-29' },
    awayTeam: { name: 'Oklahoma City Thunder', abbreviation: 'OKC', record: '57-25' },
    startTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    homeOdds: {
      moneyline: +118,
      spread: +2.5,
      spreadOdds: -112,
      total: 222.0,
      totalOddsOver: -108,
      totalOddsUnder: -112,
    },
    awayOdds: {
      moneyline: -138,
      spread: -2.5,
      spreadOdds: -108,
      total: 222.0,
      totalOddsOver: -108,
      totalOddsUnder: -112,
    },
    status: 'upcoming',
  },
  // Live NBA game
  {
    id: 'nba-3',
    sport: 'NBA',
    homeTeam: { name: 'Los Angeles Lakers', abbreviation: 'LAL', record: '45-37' },
    awayTeam: { name: 'Golden State Warriors', abbreviation: 'GSW', record: '44-38' },
    startTime: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    homeOdds: {
      moneyline: -122,
      spread: -1.5,
      spreadOdds: -110,
      total: 218.5,
      totalOddsOver: -110,
      totalOddsUnder: -110,
    },
    awayOdds: {
      moneyline: +102,
      spread: +1.5,
      spreadOdds: -110,
      total: 218.5,
      totalOddsOver: -110,
      totalOddsUnder: -110,
    },
    status: 'live',
    homeScore: 87,
    awayScore: 82,
    liveQuarter: '3rd Qtr 4:22',
  },
  // MLB
  {
    id: 'mlb-1',
    sport: 'MLB',
    homeTeam: { name: 'New York Yankees', abbreviation: 'NYY', record: '42-31' },
    awayTeam: { name: 'Boston Red Sox', abbreviation: 'BOS', record: '38-35' },
    startTime: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    homeOdds: {
      moneyline: -148,
      spread: -1.5,
      spreadOdds: +128,
      total: 8.5,
      totalOddsOver: -115,
      totalOddsUnder: -105,
    },
    awayOdds: {
      moneyline: +125,
      spread: +1.5,
      spreadOdds: -152,
      total: 8.5,
      totalOddsOver: -115,
      totalOddsUnder: -105,
    },
    status: 'upcoming',
  },
  {
    id: 'mlb-2',
    sport: 'MLB',
    homeTeam: { name: 'Los Angeles Dodgers', abbreviation: 'LAD', record: '47-25' },
    awayTeam: { name: 'San Francisco Giants', abbreviation: 'SF', record: '35-37' },
    startTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    homeOdds: {
      moneyline: -195,
      spread: -1.5,
      spreadOdds: -110,
      total: 7.5,
      totalOddsOver: -108,
      totalOddsUnder: -112,
    },
    awayOdds: {
      moneyline: +162,
      spread: +1.5,
      spreadOdds: -110,
      total: 7.5,
      totalOddsOver: -108,
      totalOddsUnder: -112,
    },
    status: 'upcoming',
  },
  {
    id: 'mlb-3',
    sport: 'MLB',
    homeTeam: { name: 'Houston Astros', abbreviation: 'HOU', record: '40-33' },
    awayTeam: { name: 'Texas Rangers', abbreviation: 'TEX', record: '36-37' },
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    homeOdds: {
      moneyline: -135,
      spread: -1.5,
      spreadOdds: +118,
      total: 9.0,
      totalOddsOver: -112,
      totalOddsUnder: -108,
    },
    awayOdds: {
      moneyline: +115,
      spread: +1.5,
      spreadOdds: -140,
      total: 9.0,
      totalOddsOver: -112,
      totalOddsUnder: -108,
    },
    status: 'live',
    homeScore: 3,
    awayScore: 1,
    liveQuarter: 'Bot 5th',
  },
  // NHL Stanley Cup
  {
    id: 'nhl-1',
    sport: 'NHL',
    homeTeam: { name: 'Florida Panthers', abbreviation: 'FLA', record: '52-21-9' },
    awayTeam: { name: 'Edmonton Oilers', abbreviation: 'EDM', record: '49-26-7' },
    startTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    homeOdds: {
      moneyline: -128,
      spread: -1.5,
      spreadOdds: +165,
      total: 6.0,
      totalOddsOver: -108,
      totalOddsUnder: -112,
    },
    awayOdds: {
      moneyline: +108,
      spread: +1.5,
      spreadOdds: -198,
      total: 6.0,
      totalOddsOver: -108,
      totalOddsUnder: -112,
    },
    status: 'upcoming',
  },
  // MMA
  {
    id: 'mma-1',
    sport: 'MMA',
    homeTeam: { name: 'Jon Jones', abbreviation: 'JON', record: '27-1-0' },
    awayTeam: { name: 'Stipe Miocic', abbreviation: 'STI', record: '20-4-0' },
    startTime: new Date(Date.now() + 28 * 60 * 60 * 1000).toISOString(),
    homeOdds: {
      moneyline: -280,
      spread: -1.5,
      spreadOdds: -110,
      total: 2.5,
      totalOddsOver: -175,
      totalOddsUnder: +145,
    },
    awayOdds: {
      moneyline: +225,
      spread: +1.5,
      spreadOdds: -110,
      total: 2.5,
      totalOddsOver: -175,
      totalOddsUnder: +145,
    },
    status: 'upcoming',
  },
]

export const MOCK_PICKS: Pick[] = [
  {
    id: 'pick-1',
    gameId: 'nba-1',
    betType: 'spread',
    teamName: 'Miami Heat',
    sport: 'NBA',
    odds: -110,
    spread: +4.5,
    displayLabel: 'Heat +4.5',
    confidence: 'high',
    units: 2,
    rationale:
      'Miami is historically elite in playoff environments. The Heat have covered the spread in 7 of their last 9 road playoff games. Boston is slight home favorites but has been inconsistent defensively in the 3rd quarter — exactly where Miami attacks. 4.5 points is more than enough cushion.',
  },
  {
    id: 'pick-2',
    gameId: 'nba-2',
    betType: 'moneyline',
    teamName: 'Denver Nuggets',
    sport: 'NBA',
    odds: +118,
    displayLabel: 'Nuggets ML',
    confidence: 'medium',
    units: 1,
    rationale:
      'OKC is the better seed but Denver has Nikola Jokic, the greatest post player of this era. At home, Jokic averages 31/13/9 in the playoffs. The +118 price is excellent value — you\'re getting a three-time MVP as a home underdog.',
  },
  {
    id: 'pick-3',
    gameId: 'mlb-1',
    betType: 'over',
    teamName: 'Over 8.5',
    sport: 'MLB',
    odds: -115,
    total: 8.5,
    displayLabel: 'Yankees/Red Sox O8.5',
    confidence: 'high',
    units: 2,
    rationale:
      'Yankees hitters are red-hot, averaging 6.2 runs over their last 10. Red Sox pitching has a 5.18 ERA at Yankee Stadium over the past 2 seasons. Wind is blowing out to center. This has double-digit run potential.',
  },
  {
    id: 'pick-4',
    gameId: 'nhl-1',
    betType: 'moneyline',
    teamName: 'Edmonton Oilers',
    sport: 'NHL',
    odds: +108,
    displayLabel: 'Oilers ML',
    confidence: 'medium',
    units: 1,
    rationale:
      'McDavid and Draisaitl are two of the most dangerous playoff performers in NHL history. Florida has home ice but the Oilers have won the last 3 road playoff games. Getting plus money on a team with arguably the best player in the sport is great value.',
  },
  {
    id: 'pick-5',
    gameId: 'mlb-2',
    betType: 'under',
    teamName: 'Under 7.5',
    sport: 'MLB',
    odds: -112,
    total: 7.5,
    displayLabel: 'Dodgers/Giants U7.5',
    confidence: 'low',
    units: 0.5,
    rationale:
      'Both starting pitchers have been elite this month. Dodger Stadium suppresses run scoring, especially in night games. The Giants have scored 2 or fewer runs in 4 of their last 6 against LA pitching.',
  },
  {
    id: 'pick-6',
    gameId: 'mma-1',
    betType: 'moneyline',
    teamName: 'Jon Jones',
    sport: 'MMA',
    odds: -280,
    displayLabel: 'Jones ML',
    confidence: 'high',
    units: 1,
    rationale:
      'Jones is the GOAT. Despite the large number, he\'s never been finished and has dominated every elite HW he\'s faced. Stipe is tough but Jones\'s wrestling, reach, and IQ make this as close to a lock as MMA gets. Lay the price.',
  },
]

export const MOCK_BET_HISTORY = [
  {
    id: 'bet-h-1',
    gameId: 'hist-1',
    sport: 'NBA' as const,
    teamName: 'Boston Celtics',
    betType: 'spread' as const,
    odds: -110,
    spread: -5.5,
    displayLabel: 'Celtics -5.5',
    stake: 110,
    placedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    result: 'win' as const,
    payout: 210,
  },
  {
    id: 'bet-h-2',
    gameId: 'hist-2',
    sport: 'MLB' as const,
    teamName: 'Dodgers',
    betType: 'moneyline' as const,
    odds: -180,
    displayLabel: 'Dodgers ML',
    stake: 180,
    placedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    result: 'win' as const,
    payout: 280,
  },
  {
    id: 'bet-h-3',
    gameId: 'hist-3',
    sport: 'NBA' as const,
    teamName: 'Heat',
    betType: 'moneyline' as const,
    odds: +155,
    displayLabel: 'Heat ML',
    stake: 100,
    placedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    result: 'loss' as const,
    payout: 0,
  },
  {
    id: 'bet-h-4',
    gameId: 'hist-4',
    sport: 'NFL' as const,
    teamName: 'Over 47.5',
    betType: 'over' as const,
    odds: -110,
    total: 47.5,
    displayLabel: 'Chiefs/Bills O47.5',
    stake: 110,
    placedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    result: 'win' as const,
    payout: 210,
  },
  {
    id: 'bet-h-5',
    gameId: 'hist-5',
    sport: 'MLB' as const,
    teamName: 'Yankees',
    betType: 'spread' as const,
    odds: -112,
    spread: -1.5,
    displayLabel: 'Yankees -1.5',
    stake: 112,
    placedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    result: 'loss' as const,
    payout: 0,
  },
  {
    id: 'bet-h-6',
    gameId: 'hist-6',
    sport: 'NHL' as const,
    teamName: 'Panthers',
    betType: 'moneyline' as const,
    odds: -138,
    displayLabel: 'Panthers ML',
    stake: 138,
    placedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    result: 'win' as const,
    payout: 238,
  },
  {
    id: 'bet-h-7',
    gameId: 'hist-7',
    sport: 'NBA' as const,
    teamName: 'Nuggets',
    betType: 'spread' as const,
    odds: -108,
    spread: -3.5,
    displayLabel: 'Nuggets -3.5',
    stake: 108,
    placedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    result: 'push' as const,
    payout: 108,
  },
]
